package = "ascii-ui.nvim"
lua = "==5.1"

[description]
summary = "A WIP extensible ui framework with no non-sense apis (hopefully) for nvim."
maintainer = "rcasia"
labels = []
license = "MIT"

[source]
url = "https://github.com/rcasia/$(PACKAGE)/archive/refs/tags/v$(VERSION).zip"

[dependencies]
"plenary.nvim" = "scm-1"

[test]
type = "command"
command = "./scripts/test_lux"

[build]
type = "builtin"
